# Generated by Django 6.0.2 on 2026-02-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('student_email', models.EmailField(max_length=120)),
                ('student_number', models.IntegerField(default=0)),
                ('student_usn', models.CharField(max_length=10)),
                ('student_branch', models.CharField(max_length=120)),
                ('student_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('student_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
